version: '3'
services:
  backend:
    build: ./fastapi_server
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_server:/app
    env_file:
      - fastapi_server/.env

  onemap-ui:
    build: ./onemap_ui
    ports:
      - "3000:3000"
    volumes:
      - ./onemap_ui:/app
      - /app/node_modules
    # environment:
    #   BACKEND_BASE_URL: "http://localhost:8080"
    #   NEXTAUTH_SECRET: "atr5-gt65-9jet"
    #   NEXTAUTH_URL: "http://localhost:3000/"
    #   NEXT_PUBLIC_BASE_URL: "http://localhost:3000"
    #   NODE_ENV: "development"